import sys
import subprocess

# Check for required Python packages
required_modules = {
    'yaml': 'PyYAML'
}

for module, package in required_modules.items():
    try:
        __import__(module)
    except ImportError:
        # Check if pip is available
        try:
            subprocess.run([sys.executable, "-m", "pip", "--version"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, check=True)
        except (subprocess.CalledProcessError, FileNotFoundError):
            print(f"Error: pip is not installed. Please install pip to proceed with installing {package}.")
            sys.exit(1)

        print(f"Installing required package: {package}")
        try:
            subprocess.check_call([sys.executable, "-m", "pip", "install", package])
        except subprocess.CalledProcessError:
            print(f"Failed to install {package}. Please install it manually by running: pip install {package}")
            sys.exit(1)

import os
import re
import yaml
import socket
import platform
import scripts.utils as utils
import scripts.git_util as git_util
IS_CI = os.getenv("CI") == "true"

if platform.system() == "Linux":
    from scripts.linux.setup_env import env_configuration
    from scripts.linux.setup_premake import premake_configuration
    import scripts.linux.IDE_setup as IDE_setup
elif platform.system() == "Windows":
    from scripts.windows.setup_env import env_configuration
    import scripts.windows.win_utils as win_util
    win_util.enable_ansi_support()
    from scripts.windows.setup_premake import premake_configuration
    import scripts.windows.IDE_setup as IDE_setup
else:
    raise Exception("Unsupported operating system")



def apply_premake_settings(file_path="./config/app_settings.yml", premake_file_path="./premake5.lua"):
    try:
        with open(file_path, 'r') as stream:
            data = yaml.safe_load(stream)
            app_name = data['general_settings']['name']
        
        # Read the premake5.lua content
        with open(premake_file_path, 'r') as file:
            content = file.read()

        # find/replace startproject name
        content = re.sub(
            r'(startproject\s*")[^"]*(")',
            r'\1' + app_name + r'\2',
            content
        )

        # find/replace project name
        content = re.sub(
            r'(project\s*")[^"]*(".*?-- generated by the setup\.py script)',
            r'\1' + app_name + r'\2',
            content
        )

        # Write the modified content back
        with open(premake_file_path, 'w') as file:
            file.write(content)
            
    except Exception as e:
        utils.print_c(f"Error while applying settings: {str(e)}", "red")
        sys.exit(1)


def get_application_name(file_path="./config/app_settings.yml"):
    try:
        with open(file_path, 'r') as stream:
            data = yaml.safe_load(stream)
            return data['general_settings']['name']
    except Exception as e:
        utils.print_c(f"Error while reading settings file: {str(e)}", "red")
        sys.exit(1)


def get_clean_build_artifacts_on_build(file_path="./config/app_settings.yml"):
    try:
        with open(file_path, 'r') as stream:
            data = yaml.safe_load(stream)
            return data['general_settings']['clean_build_artifacts_on_build']
    except Exception as e:
        utils.print_c(f"Error while reading settings file: {str(e)}", "red")
        sys.exit(1)



def main():
    # Skip internet check in CI
    if not IS_CI:
        try:
            socket.setdefaulttimeout(3)
            socket.socket(socket.AF_INET, socket.SOCK_STREAM).connect(("8.8.8.8", 53))
        except:
            utils.print_c("\nNo Internet connection found\n", "red")
            sys.exit(1)

    try:
        utils.print_u("\nCHECKING SYSTEM DEPENDENCIES")
        if not env_configuration.validate():
            utils.print_c("Missing required packages - setup aborted", "red")
            sys.exit(1)
        
        utils.print_u("\nCHECK PREMAKE-5 SETUP")
        if not premake_configuration.validate():
            utils.print_c("Premake5 download failed - setup aborted", "red")
            sys.exit(1)
    
        utils.print_u("\nINITIALIZING SUBMODULES")              # Initialize submodule configuration
        if not git_util.initialize_submodules():
            utils.print_c("Submodule initialization failed - setup aborted", "red")
            sys.exit(1)
    
        utils.print_u("\nUPDATING SUBMODULES")                  # Update submodules to desired branches
        # git_util.update_submodule("vendor/glfw", "main")
        # git_util.update_submodule("vendor/glm", "master")
        # git_util.update_submodule("vendor/imgui", "docking")
        # git_util.update_submodule("vendor/implot", "master")
        # git_util.update_submodule("vendor/Catch2", "devel")


        utils.print_u("\nAPPLY SETTINGS")
        utils.print_c("Settings are defined at [./config/app_settings.yml]. after changing the settings, it is recommended to reexecute the setup script", "blue")
        apply_premake_settings()
        application_name = get_application_name()
        clean_art_on_build = get_clean_build_artifacts_on_build()
        print(f"name: {application_name}")
        

        # setup IDE
        utils.print_u("\nSETUP IDE")

        if IS_CI:                                       # select first detected IDE in CI
            IDEs = IDE_setup.detect_IDEs()
            selected_ide = IDEs[0]
            print(f"Selected IDE: {selected_ide}")
        else:
            selected_ide = IDE_setup.prompt_ide_selection()

        # VSCode spcific setup
        if "VSCode" in selected_ide:
            if IS_CI:
                build_config = "Debug"
            else:
                build_config = IDE_setup.prompt_build_config()
            IDE_setup.setup_vscode_configs(os.getcwd(), build_config, application_name, clean_art_on_build)
        

        if platform.system() == "Linux":                # ---- LINUX VERSION ----
            # prepare premake command
            premake_action = "gmake2"  # Default to VSCode
            if selected_ide == "JetBrains Rider":
                premake_action = "rider"
            elif "VSCode" in selected_ide:
                premake_action = "gmake2"
            elif "Makefile" in selected_ide:
                premake_action = "gmake2"

            premake_result = subprocess.run(['vendor/premake/premake5', premake_action], text=True)

        else:                                           # ---- WINDOWS VERSION ----
            # prepare premake command
            premake_action = "vs2022"  # Default to VS2022
            if selected_ide == "VSCode":
                premake_action = "gmake2"  # For MinGW-based builds
            elif "Visual Studio" in selected_ide:       # Map IDE selection to premake action
                if "2022" in selected_ide:
                    premake_action = "vs2022"
                elif "2019" in selected_ide:
                    premake_action = "vs2019"
                elif "2017" in selected_ide:
                    premake_action = "vs2017"
            elif selected_ide == "JetBrains Rider":
                premake_action = "rider"
            
            premake_result = subprocess.run(['vendor\\premake\\premake5.exe', premake_action], text=True)

        if premake_result.returncode != 0:
            utils.print_c(f"BUILD FAILED! Premake script encountered errors [{premake_result.returncode}]", "red")
        else:
            utils.print_c("BUILD SUCCESSFUL!", "green")


        # print helpful hints
        if platform.system() == "Linux":                # ---- LINUX VERSION ----
            utils.print_c("\nHelpful hints", "blue")
            print("  Apply changed premake scripts:     vendor/premake/premake5 gmake2")
            print("  Cleanup generated files:           gmake clean")
            print("  Compile application:               gmake -j")
            print("  More help:                         vendor/premake/premake5 --help OR https://premake.github.io/docs/Using-Premake/")

        else:                                           # ---- WINDOWS VERSION ----
            # Print helpful hints
            utils.print_c("\nHelpful hints for Windows", "blue")
            if "Visual Studio" in selected_ide or "Rider" in selected_ide:
                print("  Open solution file:               *.sln")
                print("  Clean solution:                   msbuild /t:Clean")
                print("  Build solution:                   msbuild /t:Build")
            elif selected_ide == "VSCode":
                print("  Apply changed premake scripts:    vendor\\premake\\premake5.exe gmake2")
                print("  Clean solution:                   gmake clean")
                print("  Build solution:                   gmake -j")
            print("  More help:                        vendor\\premake\\premake5.exe --help")


    except KeyboardInterrupt:
        utils.print_c("\nProcess interrupted by user.", "red")


if __name__ == "__main__":
    main()
