general_settings:
  name: gluttony_launcher
  display_name: Gluttony Launcher
  description: This launcher manages my game engine versions, plugins and user projects
  logo_path: assets/images/logo.png
  project_version: 0 0 1
  app_namespace: AT
